{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-bridge-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.labels" . | nindent 4 }}
data:
  config.yaml: |
    schedulerName: {{ include "slurm-bridge.scheduler.name" . }}
    slurmRestApi: {{ .Values.sharedConfig.slurmRestApi }}
    {{- if .Values.admission.managedNamespaceSelector }}
    managedNamespaceSelector:
      {{- toYaml .Values.admission.managedNamespaceSelector | nindent 6 }}
    {{- else }}
    managedNamespaces:
    {{- range .Values.admission.managedNamespaces }}
      - {{ . }}
    {{- end }}
    {{- end }}
    mcsLabel: {{ .Values.schedulerConfig.mcsLabel }}
    partition: {{ .Values.schedulerConfig.partition }}
