---
apiVersion: v2
kubeVersion: ">= 1.29.0-0"

name: slurm-bridge
description: Slurm as a Kubernetes Scheduler
type: application
appVersion: "25.05"
version: 0.4.0

annotations:
  license: Apache-2.0

home: https://slinky.schedmd.com/
icon: https://github.com/SlinkyProject/docs/blob/main/docs/_static/images/slinky.svg

sources:
  - https://github.com/SlinkyProject/slurm-bridge

maintainers:
  - name: SchedMD LLC.
    email: slinky@schedmd.com
    url: https://support.schedmd.com/
